In [1]:
# imoporting modules
import pandas as pd      # its used for dataframe
import numpy as np      # its used for n dimensional array
import matplotlib.pyplot as plt     # its used for ploting the graph

In [2]:
#read csv file
data=pd.read_csv("spam.csv",encoding="latin_1")
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
#find no.of rows and columns
data.shape

(5573, 5)

In [4]:
#find if any NaN numbers is there in data
data.isnull().sum()

v1               0
v2               0
Unnamed: 2    5523
Unnamed: 3    5561
Unnamed: 4    5567
dtype: int64

In [5]:
#Drop columns
data = data.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)

In [6]:
#column names rechange
data = data.rename(columns={"v1":"label", "v2":"text"})

In [7]:
#Count observations in each label
data.label.value_counts()

ham     4826
spam     747
Name: label, dtype: int64

In [8]:
# convert label to a numerical variable
data['label_num'] = data.label.map({'ham':0, 'spam':1})

In [9]:
data.head()

  label                                               text  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [10]:
data['length'] = data['text'].apply(len)
data.head()

  label                                               text  label_num  length
0   ham  Go until jurong point, crazy.. Available only ...          0     111
1   ham                      Ok lar... Joking wif u oni...          0      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1     155
3   ham  U dun say so early hor... U c already then say...          0      49
4   ham  Nah I don't think he goes to usf, he lives aro...          0      61

In [11]:
x=np.array(data['text'])
x
data.shape

(5573, 4)

In [12]:
y = np.array(data['label_num'])
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [13]:
conda install -c anaconda seaborn

Note: you may need to restart the kernel to use updated packages.

In [14]:
import seaborn as sns
sns.countplot(data["label"])
plt.show()

ValueError: could not convert string to float: 'ham'

In [ ]:
data["label"].value_counts().plot(kind="pie",autopct="%1.1f%%")
plt.axis("equal")
plt.show()

In [ ]:
spam1=data.loc[data['label']=='spam']
spam1["text"].head()

In [ ]:
ham1=data.loc[data['label']=='ham']
ham1["text"].head()

In [ ]:
x_train=np.array(data.iloc[0:500,1])
x_train.shape

In [ ]:
y_train=np.array(data.iloc[0:500,0])
y_train[0:5]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
print(count_vector)

In [ ]:
train_data = count_vector.fit_transform(x_train)
test_data = count_vector.transform(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()
model.fit(train_data,y_train)

In [ ]:
pred=model.predict(test_data)
pred

In [ ]:
model.score(test_data,y_test)

In [ ]:
from sklearn.metrics import classification_report
nbreport=classification_report(y_test, pred)
print(nbreport)

In [ ]:
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [ ]:
y=[f1_score(y_test,pred),recall_score(y_test,pred),precision_score(y_test,pred)]

In [ ]:
x=["f1score","recall","precision"]
y=[f1_score(y_test,pred),recall_score(y_test,pred),precision_score(y_test,pred)]
df = pd.DataFrame(dict(x=x, y=y))
df

In [ ]:
sns.factorplot("x","y", data=df,kind="bar")
plt.show()

In [ ]:
sns.barplot("x","y", data=df)
plt.show()

In [ ]:
plt.pie(y,labels=x,autopct='%1.1f%%')
plt.axis("equal")
plt.show()

In [ ]:
#creating testing data
x_test=[ "hi how are you",
        "Free entry in 2 a wkly comp to win FA Cup fina...",
        "when will you go to home",
        "i will call you back",
        "are you busy now"]

In [ ]:
x_test.append("goodmoring")
x_test.append("WINNER!! As a valued network customer you have...")

In [ ]:
x_test

In [ ]:
x_test1=np.array(x_test)
x_test1

In [ ]:
X_train=data.iloc[0:200,1]
X_train[0:6]

In [ ]:
Y_train=data.iloc[0:200,0]
Y_train[0:5]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
print(count_vector)

In [ ]:
train_data = count_vector.fit_transform(X_train)
test_data = count_vector.transform(x_test1)

In [ ]:
train_data.shape

In [ ]:
test_data.shape

In [ ]:
Y_train.shape

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()
model.fit(train_data,Y_train)

In [ ]:
pred=model.predict(test_data)
pred

In [ ]:
y1=model.predict(test_data)

In [ ]:
y1

In [ ]:
df = pd.DataFrame(dict(INPUT=x_test1, OUTPUT=y1))
df

In [ ]:
df.iloc[4:]